#!/usr/bin/env python
# encoding: utf-8
from setuptools import setup, find_packages

setup(
    name='acac_marl',
    version='1.0.0',
    author='Whiyoung Jung, Sunghoon Hong, Deunsol Yoon, Kanghoon Lee, Woohyung Lim', 
    author_email='[whiyoung.jung, sunghoon.hong, dsyoon, kanghoon.lee, w.lim]@lgresearch.ai',
    description='Official code for Agent-Centric Actor-Critic for Multi-Agent Reinforcement Learning (ICML 2025)',
    packages=find_packages(),
    classifiers=[
        'Programming Language :: Python :: 3',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.9',
    install_requires=[
        'absl-py==0.15.0',
        'astunparse==1.6.3',
        'backcall==0.2.0',
        'cachetools==4.2.4',
        'charset-normalizer==2.0.7',
        'clang==5.0',
        'cloudpickle==2.0.0',
        'cycler==0.11.0',
        'decorator==5.1.0',
        'flatbuffers==1.12',
        'gast==0.4.0',
        'google-auth==2.3.3',
        'google-auth-oauthlib==0.4.6',
        'google-pasta==0.2.0',
        'grpcio==1.41.1',
        'gym==0.22.0',
        'h5py==3.1.0',
        'idna==3.3',
        'ipdb==0.13.9',
        'ipython==7.29.0',
        'jedi==0.18.0',
        'keras==2.6.0',
        'keras-preprocessing==1.1.2',
        'kiwisolver==1.3.2',
        'markdown==3.3.4',
        'matplotlib==3.4.3',
        'matplotlib-inline==0.1.3',
        'networkx==3.2.1',
        'numpy==1.21.5',
        'oauthlib==3.1.1',
        'opt-einsum==3.3.0',
        'pandas==1.3.4',
        'parso==0.8.2',
        'pexpect==4.8.0',
        'pickleshare==0.7.5',
        'pillow==8.4.0',
        'prompt-toolkit==3.0.21',
        'protobuf==3.19.1',
        'ptyprocess==0.7.0',
        'pyasn1==0.4.8',
        'pyasn1-modules==0.2.8',
        'pygame==2.0.3',
        'pyglet==1.5.26',
        'pygments==2.10.0',
        'pyparsing==3.0.4',
        'python-dateutil==2.8.2',
        'pytz==2021.3',
        'pyvirtualdisplay==3.0',
        'requests==2.26.0',
        'requests-oauthlib==1.3.0',
        'rsa==4.7.2',
        'seaborn==0.11.2',
        'six==1.15.0',
        'termcolor==1.1.0',
        'toml==0.10.2',
        'traitlets==5.1.1',
        'typing-extensions==3.7.4.3',
        'urllib3==1.26.7',
        'wcwidth==0.2.5',
        'werkzeug==2.0.2',
        'wrapt==1.12.1',
        'pybullet==3.0.6',
        'future==0.18.2',
        'pyyaml==5.3.1',
        'munch==2.5.0',
        'jupyter==1.0.0',
        'jupyter_client==7.4.8',
        'jupyter-console==6.4.4',
        'jupyter_core==4.12.0',
        'jupyter-server==1.24.0',
        'qtconsole==5.6.1',
        'tqdm==4.49.0',
        'Cython==0.29.21',
        'fpdf==1.7.2',
        'anki-vector==0.6.0',
        'zeroconf==0.24.0',
        'transformers==4.28.1',
        'wandb',
    ],
)